package com.test.exception;

public class TestDemoException {
	// static ArithmeticException e=new ArithmeticException();
	public static void main(String[] args) throws CustomException {
		// for(int j = 1; j<=10; j++) {
		// System.out.println("J "+j);
		// for(int i = 1; i<=10; i++) {
		// if(i%2 == 0) {
		// System.out.println("breaking "+i);
		// break;
		// }
		// System.out.println(i);
		// }
		// if(j == 4) {
		// System.out.println("breaking "+j);
		// break;
		// }
		// }
		// if(a<b) {
		// throw new CustomException("a value should be greater than b");
		// }
		// if(a<b) {
		// throw new CustomException();
		// }
		// TODO Auto-generated method stub
		// System.out.println("State - 1");

		System.out.println(foo1(11));
	}

	public static void foo() {
		//foo1();
	}

	public static int foo1(int b) {
    for(int i =0; i<15;i++) {
    	if(i == 10) {
        	return 1000;
        }
    	if(i == 5) {
        	return 5000;
        }
    	if(i == 7) {
        	return 7000;
        }else {
        	return 123456;
        }
    }
	}
}
